
version: "3.5"

services:
  theisland:
    image: fossum/ark-cluster:master

    # healthcheck:
    #   test: arkmanager status | grep 'Server listening:.\+No' && exit 1
    #   interval: 60s
    #   retries: 5
    #   start_period: 600s
    #   timeout: 10s

    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 600s
      mode: replicated
      replicas: 1
      resources:
        reservations:
          memory: 8gb
      update_config:
        parallelism: 1
        delay: 30s
        order: stop-first
        failure_action: rollback

    environment:
      SERVER_MAP: "TheIsland"
      SESSION_NAME: "ARK Cluster TheIsland"
      CRON_AUTO_UPDATE: ${CRON_AUTO_UPDATE:-0 */3 * * *}
      CRON_AUTO_BACKUP: ${CRON_AUTO_BACKUP:-0 */1 * * *}
      UPDATE_ON_START: ${UPDATEONSTART:-1}
      BACKUP_ON_START: ${BACKUPONSTART:-1}
      BACKUP_ON_STOP: ${BACKUPONSTOP:-1}
      WARN_ON_STOP: ${WARNONSTOP:-1}
      USER_ID: ${USER_ID:-1000}
      GROUP_ID: ${GROUP_ID:-1000}
      TZ: ${TZ:-UTC}
      MAX_BACKUP_SIZE: ${MAX_BACKUP_SIZE:-1}
      MAX_PLAYERS: ${MAX_PLAYERS:-15}
      RCON_ENABLE: ${RCON_ENABLE:-True}
      RCON_PORT: ${RCON_PORT:-32332}
      GAME_PORT: ${GAME_PORT:-7781}
      QUERY_PORT: ${QUERY_PORT:-27017}
      SERVER_PASSWORD: ${SERVER_PASSWORD}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-keepmesecret}
      SPECTATOR_PASSWORD: ${SPECTATOR_PASSWORD:-keepmesecret}
      MODS: ${MODS}
      CLUSTER_ID: ${CLUSTER_ID}
      KILL_PROCESS_TIMEOUT: ${KILL_PROCESS_TIMEOUT:-300}
      KILL_ALL_PROCESSES_TIMEOUT: ${KILL_ALL_PROCESSES_TIMEOUT:-300}

    volumes:
      - island:/ark
      - cluster:/cluster

    ports:
      - "32332:32332/tcp"
      - "7781:7781/udp"
      - "7782:7782/udp"
      - "27017:27017/udp"

  valguero:
    image: fossum/ark-cluster:master
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 600s
      mode: replicated
      replicas: 1
      resources:
        reservations:
          memory: 8gb
      update_config:
        parallelism: 1
        delay: 30s
        order: stop-first
        failure_action: rollback
    environment:
      SERVER_MAP: "Valguero_P"
      SESSION_NAME: "ARK Cluster"
      RCON_PORT: ${RCON_PORT:-32331}
      GAME_PORT: ${GAME_PORT:-7779}
      QUERY_PORT: ${QUERY_PORT:-27016}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-keepmesecret}
      SPECTATOR_PASSWORD: ${SPECTATOR_PASSWORD:-keepmesecret}
      CLUSTER_ID: ${CLUSTER_ID}

    volumes:
      - valguero:/ark
      - cluster:/cluster

    ports:
      - "32331:32331/tcp"
      - "7779:7779/udp"
      - "7780:7780/udp"
      - "27016:27016/udp"

volumes:
  island:
  valguero:
  cluster:
